# Generated by Django 3.1.7 on 2021-03-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direcion', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=50)),
                ('observacion', models.TextField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('costo', models.IntegerField()),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direcion', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=50)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraEntrada', models.DateTimeField()),
                ('fechaHoraSalida', models.DateTimeField()),
                ('costoTotal', models.IntegerField()),
                ('observacion', models.TextField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.estado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.habitacion')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.registrador')),
            ],
        ),
    ]
